# 定义workflow名称 
name: Sync archive folder

# 在A仓库main分支push代码时触发
on: 
  push:
    branches:
      - main

# 定义任务    
jobs:

# 任务名称 
  build: 
  
# 在ubuntu环境下运行   
    runs-on: ubuntu-latest
    
    steps:
    
# 检出A仓库代码    
    - uses: actions/checkout@v2

    - name: Compute archive hash
      run: |
        HASH=$(sha1sum archive | awk '{print $1}')
        echo "HASH=${HASH}" >> $GITHUB_ENV

    - name: Check if archive changed
      run: |    
        NEW_HASH=$(sha1sum archive | awk '{print $1}')
        if [ "$NEW_HASH" = "$HASH" ]; then
          echo "Archive not changed, skip sync"
          exit 0
        fi

# 压缩archive文件夹为zip包    
    - name: Zip archive folder
      run: |
        zip -r ../archive.zip ./archive
        
  # 检出B仓库代码    
    - name: Extract archive 
      uses: actions/checkout@v2
      with:
        repository: Ark2000/testsync
        token: ${{ secrets.TOKEN }}
      
# 解压zip包并覆盖文件    
    - run: |
        rm -rf *
        unzip ../archive.zip
        cp -r archive/* ./
        rm -rf archive
        ls -a

        
# 提交并推送变更到B仓库    
    - name: Commit and push
      run: |
        git config user.name bot-k2kra
        git config user.email ark2000@foxmail.com
        git add .
        git commit -m "Sync archive"
        git push
        echo "git push output: $?"